CREATE TABLE transit_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    transport_type VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_provider_transport_type
        CHECK (transport_type IN ('BUS', 'SUBWAY'))
);

CREATE TABLE transit_line (
    id UUID PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES transit_provider (id),
    provider_line_id VARCHAR(100) NOT NULL,
    public_name VARCHAR(100) NOT NULL,
    operator_name VARCHAR(100),
    route_type VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_line_provider_resource
        UNIQUE (provider_id, provider_line_id)
);

CREATE TABLE transit_stop (
    id UUID PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES transit_provider (id),
    provider_stop_id VARCHAR(100) NOT NULL,
    parent_station_id UUID REFERENCES transit_stop (id),
    public_name VARCHAR(150) NOT NULL,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_stop_provider_resource
        UNIQUE (provider_id, provider_stop_id),
    CONSTRAINT ck_stop_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_stop_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

INSERT INTO transit_provider (code, display_name, transport_type)
VALUES
    ('GBIS', '경기버스정보', 'BUS'),
    ('NATIONAL_PRECISION_BUS', '전국 초정밀버스', 'BUS'),
    ('SEOUL_SUBWAY', '서울 지하철', 'SUBWAY');
