CREATE TABLE raw_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES transit_provider (id),
    endpoint VARCHAR(200) NOT NULL,
    request_key VARCHAR(300) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    provider_observed_at TIMESTAMPTZ,
    response_status INTEGER NOT NULL,
    payload JSONB,
    expires_at TIMESTAMPTZ,
    CONSTRAINT ck_raw_observation_status
        CHECK (response_status BETWEEN 100 AND 599),
    CONSTRAINT ck_raw_observation_expiry
        CHECK (expires_at IS NULL OR expires_at >= received_at)
);

COMMENT ON COLUMN raw_observation.request_key IS
    'Authentication data removed; contains only a canonical non-secret request identifier.';

COMMENT ON COLUMN raw_observation.payload IS
    'Nullable when provider terms do not permit raw response retention.';
