CREATE TABLE vehicle_run_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_observation_id BIGINT REFERENCES raw_observation (id) ON DELETE SET NULL,
    line_id UUID NOT NULL REFERENCES transit_line (id),
    direction_id UUID REFERENCES route_direction (id),
    stop_pattern_id UUID REFERENCES stop_pattern (id),
    provider_vehicle_id VARCHAR(100) NOT NULL,
    provider_run_id VARCHAR(100),
    destination_stop_id UUID REFERENCES transit_stop (id),
    current_stop_id UUID REFERENCES transit_stop (id),
    current_sequence INTEGER,
    service_type VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    movement_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    speed_kph NUMERIC(7, 2),
    bearing_degrees NUMERIC(6, 2),
    position_source VARCHAR(20) NOT NULL DEFAULT 'STOP_SEQUENCE',
    observed_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_vehicle_current_sequence
        CHECK (current_sequence IS NULL OR current_sequence >= 0),
    CONSTRAINT ck_vehicle_service_type
        CHECK (service_type IN ('LOCAL', 'EXPRESS', 'RAPID', 'CIRCULAR', 'SHUTTLE', 'UNKNOWN')),
    CONSTRAINT ck_vehicle_movement_status
        CHECK (movement_status IN ('APPROACHING', 'ARRIVED', 'DEPARTED', 'BETWEEN', 'UNKNOWN')),
    CONSTRAINT ck_vehicle_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_vehicle_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_vehicle_speed
        CHECK (speed_kph IS NULL OR speed_kph >= 0),
    CONSTRAINT ck_vehicle_bearing
        CHECK (bearing_degrees IS NULL OR (bearing_degrees >= 0 AND bearing_degrees < 360)),
    CONSTRAINT ck_vehicle_position_source
        CHECK (position_source IN ('STOP_SEQUENCE', 'GPS', 'GNSS', 'ESTIMATED'))
);

CREATE TABLE arrival_prediction_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_observation_id BIGINT REFERENCES raw_observation (id) ON DELETE SET NULL,
    vehicle_run_observation_id BIGINT REFERENCES vehicle_run_observation (id) ON DELETE SET NULL,
    boarding_stop_id UUID NOT NULL REFERENCES transit_stop (id),
    expected_at TIMESTAMPTZ,
    min_expected_at TIMESTAMPTZ,
    max_expected_at TIMESTAMPTZ,
    remaining_stops INTEGER,
    source VARCHAR(20) NOT NULL,
    confidence VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    observed_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_arrival_remaining_stops
        CHECK (remaining_stops IS NULL OR remaining_stops >= 0),
    CONSTRAINT ck_arrival_source
        CHECK (source IN ('PROVIDER', 'CALCULATED', 'TIMETABLE')),
    CONSTRAINT ck_arrival_confidence
        CHECK (confidence IN ('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN')),
    CONSTRAINT ck_arrival_expected_range
        CHECK (
            (min_expected_at IS NULL OR expected_at IS NULL OR min_expected_at <= expected_at)
            AND (max_expected_at IS NULL OR expected_at IS NULL OR expected_at <= max_expected_at)
            AND (min_expected_at IS NULL OR max_expected_at IS NULL OR min_expected_at <= max_expected_at)
        )
);
